# Generated by Django 4.2.4 on 2023-08-05 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
